build:
  test:
    image: node:6.3.0
    environment:
      - DEVICE_IP=localhost
      - DEVICE_ID=test
      - MQTT_BROKER=localhost
      - MQTT_BROKER_USER=
      - MQTT_BROKER_PASS=
    commands:
      - npm test

publish:  
  docker:
    username: drone
    password: drone
    email: drone@vizcom.com.au
    mirror: https://docker-virtual.artifactory.internal.vizcom.com.au
    repo: vizcom/display-node
    registry: docker-virtual.artifactory.internal.vizcom.com.au
    tag:
      - production
      - "$$BUILD_NUMBER"
    file: Dockerfile
    insecure: true
    storage_driver: vfs

deploy:
  marathon:
    image: docker-vizconnect.artifactory.internal.vizcom.com.au/vizcom/drone-marathon
    server: https://admin:Pv4bUN8_dT365CsY@mantl-control-02.dev.internal.vizcom.com.au:8080
    id: /vizconnect/room/display-node
    instances: 1
    cpus: 0.1
    mem: 64
    docker_image: docker-vizconnect.artifactory.internal.vizcom.com.au/vizcom/display-node:$$BUILD_NUMBER